### ISSUE TITLE
switch to using electron

### ISSUE THREAD

**Issue by raymonable** [MissingNO123/spotify-vrchat-status#3]
if you still care about tihs project

you should consider switching to using electron to open the spotify login window
it wouldn't be as performant but would be much more elegant

**Comment by MissingNO123** [comment]
Using electron comes with a plethora of issues aside from performance, like the fact that it would not have access to your browser cookies forcing you to log in manually, or that it would over-complicate the codebase to fix one minor annoyance, or that it would massively increase the memory footprint of the program, or the fact that I personally dislike electron. 

Being that it's an open-source program, anyone is free to create a fork of the repo and add it if they so desire.
